gate7:
	go run Server.go /Users/justcy/Documents/Develop/go/src/github.com/justcy/ygo/examples/conf/7777.conf /Users/justcy/Documents/Develop/go/src/github.com/justcy/ygo/examples/log/7777
gate6:
	go run Server.go /Users/justcy/Documents/Develop/go/src/github.com/justcy/ygo/examples/conf/6666.conf /Users/justcy/Documents/Develop/go/src/github.com/justcy/ygo/examples/log/6666

